### ISSUE TITLE
运行检查master的ip与本机ip一样。但是说应该在master上运行。逻辑有问题？

### ISSUE THREAD

**Issue by gohell9** [abcfyk/setup_cdh#1]
[root@m1 install]**# ifconfig**
ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet **192.168.83.45**  netmask 25xxxxx5.0  broadcast 1xxxxxx255
        inet6 2001:250:5xxxxx:3xxxxxx56:c245:a271  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::9xxxxxxxxxxxx3d  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:94:97:48  txqueuelen 1000  (Ethernet)
        RX packets 6109722  bytes 8806729682 (8.2 GiB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 2670507  bytes 5253109254 (4.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 702615  bytes 5027600513 (4.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 702615  bytes 5027600513 (4.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@m1 install]# hostname
m1
[root@m1 install]# vim /etc/hosts
[root@m1 install]# vim /etc/hostname
[root@m1 install]# chmod 777 ./*
[root@m1 install]# sh installcdhmeta.sh 
checking system...
checking ip...
, **exit.Script must be run in master machine. try run this script on 192.168.83.45**
[root@m1 install]# sh installcdhmeta.sh 
checking system...
checking ip...
, **exit.Script must be run in master machine. try run this script on 192.168.83.45**

**Comment by gohell9** [comment]
还有，我理解的cluster.list是只有几行主机的ip地址就可以了？理解的对吗？

**Comment by ummmme** [comment]
cluster.list只需要把要搭建集群的服务器的私有地址，每行一个
第一行必须是运行脚本那台服务器的IP
